### ISSUE TITLE
Naming for Swift protocols, classes, structs

### ISSUE THREAD

**Issue by dan12411** [Make-a-good-soup/fugle-realtime-swift#2]
命名原則可參考：
- 避免泛用的命名，例如：Manager。
- 命名思路：它拿來做什麼用、它的目標是什麼。
- 避免後面加上 Type，例如：

Bad:
```swift
struct UserStruct {}

protocol UserRepositoryProtocol {}
```

Good:
```swift
struct User {}

prtocol UserRepository {}

// implementations
class CoreDataUserRepository: UserRepository {}
class InMemoryUserRepository: UserRepository {}
```

- [Reference](https://www.youtube.com/watch?v=Xj_IZFmty6g&t=326s)

-- 

基於以上原則，原本的`FinanceProtocol`會建議其他命名，例如 `IntradayLoader`，實作的 class 可以命名為 `RemoteIntradayLoader` or `FugleIntradayLoader` 等等。

@nick45chen

**Comment by nick45chen** [comment]
好像直接叫 `FugleRealtime` 也可以 😂

**Comment by dan12411** [comment]
> 好像直接叫 `FugleRealtime` 也可以 😂

是指介面還是實作的名稱呢～不過只叫 `FugleRealtime`，無法看出他的職責，看不出來是 `Data`、`DataLodaer` 等等 🤔

**Comment by dan12411** [comment]
已實作，closed。
